name: Tests-Activate

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Set up Python and Checkout Repository
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Run Unit-Tests
      run: python Tests-Activate.py
